slug = "flute"
title = "A flute"
date = "2026-09-15"
build_type = "webapp"
template = "template.html"
description = "Acoustic flute customizer and physical modelling synthesis simulator."
extra_paths = []
routes = false
